version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre-build phases
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - zip output dist/*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - output.zip